name: "Ceph.is website redirection creation"

on:
  issues:
    types:
      - opened

permissions:
  issues: write

jobs:
  create entry:
    runs-on: ubuntu-latest
    steps:
#      - uses: alex-page/github-project-automation-plus@v0.8.0
#        with:
#          project: Validator
#          column: To triage
#          repo-token: ${{ secrets.GHPROJECT_TOKEN }}

