name: "Ceph.is website redirection creation"

on:
  issues:
    types:
      - opened

permissions:
  issues: write

jobs:
  create_entry:
    runs-on: ubuntu-latest
    steps:
      - id: get_redir_details
        run: |
          echo "github.event.issue.body" >> body.txt
      - uses: actions-go/push@v1
        with:
          author-email: "squad@cephalopod.equipment"
          author-name: "Cephalopod Equipment"
          commit-message: "[auto] added redirection"
          fail-if-empty: true

