name: "Ceph.is website redirection creation"

on:
  issues:
    types:
      - opened

permissions:
  issues: write
  contents: write

jobs:
  create_entry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get_redir_details
        run: |
          ENDPOINT="${{ fromJSON(github.event.issue.body).endpoint }}"
          URL="${{ fromJSON(github.event.issue.body).url }}"
          MESSAGE="${{ fromJSON(github.event.issue.body).message }}"
          TARGET="docs/${ENDPOINT}"
          mkdir -p "$(dirname "$TARGET")"
          echo "$URL, $MESSAGE" > "$TARGET"
      - uses: actions-go/push@v1
        with:
          commit-files: "docs/${{ fromJSON(github.event.issue.body).endpoint }}"
          author-email: "squad@cephalopod.equipment"
          author-name: "Cephalopod Equipment"
          commit-message: "for added redirection ${{ fromJSON(github.event.issue.body).target }}"
          fail-if-empty: true

