name: "Ceph.is website redirection creation"

on:
  issues:
    types:
      - opened

permissions:
  issues: write

jobs:
  create_entry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get_redir_details
        run: |
          echo "${{ github.ref }}"
          echo "${{ fromJSON(github.event.issue.body).url }}" >> body.txt
      - uses: actions-go/push@v1
        with:
          commit-files: body.txt
          author-email: "squad@cephalopod.equipment"
          author-name: "Cephalopod Equipment"
          commit-message: "[auto] added redirection"
          fail-if-empty: true

