name: "Ceph.is website redirection creation"

on:
  issues:
    types:
      - opened

permissions:
  issues: write
  contents: write

jobs:
  create_entry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get_redir_details
        run: |
          ENDPOINT="${{ fromJSON(github.event.issue.body).endpoint }}"
          URL="${{ fromJSON(github.event.issue.body).url }}"
          MESSAGE="${{ fromJSON(github.event.issue.body).message }}"
          TARGET="docs/${ENDPOINT}.html"
          mkdir -p "$(dirname "$TARGET")"
          sed "s,XXXURLXXX,${URL},g" templates/redir.tmpl > "$TARGET"
          sed -i "s/<!--XXXMESSAGEXXX-->/${MESSAGE}/" "$TARGET"
      - uses: actions-go/push@v1
        with:
          commit-files: "docs/${{ fromJSON(github.event.issue.body).endpoint }}.html"
          author-email: "squad@cephalopod.equipment"
          author-name: "Cephalopod Equipment"
          commit-message: "for added redirection ${{ fromJSON(github.event.issue.body).target }}"
          fail-if-empty: true
#      - uses: peter-evans/close-issue@v1
#        with:
#          comment: |
#            Website updated.
#            Closing issue.
      - uses: actions/stale@v4
        with:
          close-issue-message: "Website updated. Closing issue."
          days-before-stale: 0
          days-before-close: 0

