name: "Ceph.is website redirection creation"

on:
  issues:
    types:
      - opened

permissions:
  issues: write
  contents: write

jobs:
  create_entry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get_redir_details
        run: |
          mkdir -p "$(dirname "${{ fromJSON(github.event.issue.body).target }}")"
          echo "Result" > "${{ fromJSON(github.event.issue.body).target }}"
      - uses: actions-go/push@v1
        with:
          commit-files: "${{ fromJSON(github.event.issue.body).target }}"
          author-email: "squad@cephalopod.equipment"
          author-name: "Cephalopod Equipment"
          commit-message: "for added redirection ${{ fromJSON(github.event.issue.body).target }}"
          fail-if-empty: true

